const express = require('express')
const router = express.Router()
const authController = require('../controllers/auth') 
const homeController = require('../controllers/home')
const aboutController = require('../controllers/about')
const publicController = require('../controllers/public')
const followersController = require('../controllers/followers')
const followingController = require('../controllers/following')
const postsController = require("../controllers/posts")
const { ensureAuth, ensureGuest } = require('../middleware/auth')

router.get('/', homeController.getIndex)
router.get('/profile', ensureAuth, postsController.getProfile)
router.get('/public', ensureAuth, publicController.getPublic)
router.get('/followers', ensureAuth, followersController.getFollowers)
router.get('/following', ensureAuth, followingController.getFollowing)
router.get('/about', aboutController.getAbout)
router.get('/login', authController.getLogin)
router.post('/login', authController.postLogin)
router.get('/logout', authController.logout)
router.get('/signup', authController.getSignup)
router.post('/signup', authController.postSignup)

module.exports = router